"""empty message

Revision ID: fc60055da9ff
Revises: 
Create Date: 2021-06-12 00:05:36.470477

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fc60055da9ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('city', sa.String(length=120), nullable=False),
                    sa.Column('state', sa.String(length=120), nullable=False),
                    sa.Column('phone', sa.String(length=120), nullable=True),
                    sa.Column('genres', sa.ARRAY(sa.String()), nullable=False),
                    sa.Column('facebook_link', sa.String(length=120), nullable=True),
                    sa.Column('image_link', sa.String(length=500), nullable=True),
                    sa.Column('website_link', sa.String(length=500), nullable=True),
                    sa.Column('seeking_venue', sa.Boolean(), nullable=False),
                    sa.Column('seeking_description', sa.String(length=500), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('venues',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('city', sa.String(length=120), nullable=False),
                    sa.Column('state', sa.String(length=120), nullable=False),
                    sa.Column('address', sa.String(length=120), nullable=False),
                    sa.Column('phone', sa.String(length=120), nullable=True),
                    sa.Column('genres', sa.ARRAY(sa.String()), nullable=False),
                    sa.Column('facebook_link', sa.String(length=120), nullable=True),
                    sa.Column('image_link', sa.String(length=500), nullable=True),
                    sa.Column('website_link', sa.String(length=500), nullable=True),
                    sa.Column('seeking_talent', sa.Boolean(), nullable=False),
                    sa.Column('seeking_description', sa.String(length=500), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('artist_and_venue_shows',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('venue_id', sa.Integer(), nullable=True),
                    sa.Column('artist_id', sa.Integer(), nullable=True),
                    sa.Column('start_time', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_and_venue_shows')
    op.drop_table('venues')
    op.drop_table('artists')
    # ### end Alembic commands ###
